## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/"
  to = "https://www.airbnb.com/users/show/103213381"
  status = 200
  force = true # COMMENT: ensure that we always redirect
